name: CI/CD Pipeline

on:
  workflow_dispatch: # æ‰‹åŠ¨è§¦å‘
  repository_dispatch: # é€šè¿‡ API è§¦å‘
  # æ³¨æ„: GitHub Actions ä¸ç›´æ¥æ”¯æŒå¿½ç•¥æ¨é€äº‹ä»¶ï¼Œä½†ä½ å¯ä»¥é€‰æ‹©ä¸åˆ—å‡º push äº‹ä»¶æ¥è¾¾åˆ°ç›¸ä¼¼æ•ˆæœ

jobs:
  notify_start:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'push' }} # å¿½ç•¥ push äº‹ä»¶
    steps:
      - name: Notify Start
        run: |
          PIPELINE_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl -X POST -H "Content-Type: application/json" -d "{\"msgtype\": \"markdown\", \"markdown\": {\"content\": \"ğŸš€ æ„å»ºå¼€å§‹ [æŸ¥çœ‹æ§åˆ¶å°]($PIPELINE_URL)\"}}" ${{ secrets.WEB_HOOK_URL }}

  build:
    needs: notify_start
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'push' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          java -version
          mvn clean package
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: jetbrains-license.jar
          path: target/jetbrains-license.jar
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'push' && success() }}
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: jetbrains-license.jar
          path: target
      - name: Deploy
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} "cp /opt/module/jetbrains-license/jetbrains-license.jar /opt/module/jetbrains-license/jetbrains-license_$(date +\"%Y%m%d%H%M\").jar"
          scp target/jetbrains-license.jar ${{ secrets.USER }}@${{ secrets.HOST }}:/opt/module/jetbrains-license/jetbrains-license.jar
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} "/opt/module/jetbrains-license/startup.sh"

  notify_success:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'push' && success() }}
    steps:
      - name: Notify Success
        run: |
          PIPELINE_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl -X POST -H "Content-Type: application/json" -d "{\"msgtype\": \"markdown\", \"markdown\": {\"content\": \"ğŸ‰ æ„å»ºæˆåŠŸ [æŸ¥çœ‹æ§åˆ¶å°]($PIPELINE_URL)\"}}" ${{ secrets.WEB_HOOK_URL }}

  notify_failure:
    needs: [build, deploy]
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'push' && failure() }}
    steps:
      - name: Notify Failure
        run: |
          PIPELINE_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl -X POST -H "Content-Type: application/json" -d "{\"msgtype\": \"markdown\", \"markdown\": {\"content\": \"âŒ æ„å»ºå¤±è´¥ [æŸ¥çœ‹æ§åˆ¶å°]($PIPELINE_URL)\"}}" ${{ secrets.WEB_HOOK_URL }}
